### ISSUE TITLE
兄弟们，这个插件值不值得入手

### ISSUE THREAD

**Issue by ManInTheWind** [wbget/uuid-int#1]
兄弟们，这个插件值不值得入手😂

**Comment by ManInTheWind** [comment]
我是用起来，感觉也挺好使的，就是不知道在项目中用会出啥问题没

**Comment by wbget** [comment]
就是个普通的id生成器，我自己的项目在用，目前还没出啥幺蛾子。

**Comment by ManInTheWind** [comment]
![image](https://user-images.githubusercontent.com/32859126/121761042-4f242580-cb60-11eb-85b2-92e100487d72.png)
今天在mac出现这个不适用问题，咋解决呢

**Comment by wbget** [comment]
> ![image](https://user-images.githubusercontent.com/32859126/121761042-4f242580-cb60-11eb-85b2-92e100487d72.png)
> 今天在mac出现这个不适用问题，咋解决呢
修改包，没改对。用最新版本就好

**Comment by ManInTheWind** [comment]
好的，谢谢老哥
